databases:
  - name: db
    databaseName: incidencias_db
    user: incidencias_user
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: web
    env: docker
    plan: free
    dockerCommand: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               daphne -b 0.0.0.0 -p 8000 gestion_incidencias.asgi:application"
    envVars:
      - key: DB_NAME
        fromDatabase:
          name: db
          property: database
      - key: DB_USER
        fromDatabase:
          name: db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: db
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
