# Generated by Django 5.2.12 on 2026-03-21 20:23

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.ForeignKey(default=tickets.models.get_default_estado, on_delete=django.db.models.deletion.PROTECT, to='tickets.estado'),
        ),
    ]
