# Generated by Django 5.2.12 on 2026-03-26 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_incidencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_destino',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('asignacion', 'Asignación'), ('estado', 'Cambio de Estado'), ('comentario', 'Nuevo Comentario'), ('nueva_incidencia', 'Nueva Incidencia'), ('incidencia_resuelta', 'Incidencia Resuelta'), ('desasignacion', 'Desasignación')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tickets.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recibida'],
                'unique_together': {('usuario', 'notificacion')},
            },
        ),
    ]
